In [1]:
import pandas as pd

In [3]:
df=pd.read_excel(r"C:\Users\Yuvaraj S\OneDrive\Desktop\16MLP\weather_forecast.xlsx")
df

     Outlook Temperature Humidity   Windy Play
0      Sunny         Hot     High    Weak   No
1      Sunny         Hot     High  Strong   No
2   Overcast         Hot     High    Weak  Yes
3       Rain        Mild     High    Weak  Yes
4       Rain        Cool   Normal    Weak  Yes
5       Rain        Cool   Normal  Strong   No
6   Overcast        Cool   Normal  Strong  Yes
7      Sunny        Mild     High    Weak   No
8      Sunny        Cool   Normal    Weak  Yes
9       Rain        Mild   Normal    Weak  Yes
10     Sunny        Mild   Normal  Strong  Yes
11  Overcast        Mild     High  Strong  Yes
12  Overcast         Hot   Normal    Weak  Yes
13      Rain        Mild     High  Strong   No

In [6]:
from sklearn.preprocessing import LabelEncoder

In [8]:
le = LabelEncoder()
df['Outlook'] = le.fit_transform(df['Outlook'])
df

    Outlook Temperature Humidity   Windy Play
0         2         Hot     High    Weak   No
1         2         Hot     High  Strong   No
2         0         Hot     High    Weak  Yes
3         1        Mild     High    Weak  Yes
4         1        Cool   Normal    Weak  Yes
5         1        Cool   Normal  Strong   No
6         0        Cool   Normal  Strong  Yes
7         2        Mild     High    Weak   No
8         2        Cool   Normal    Weak  Yes
9         1        Mild   Normal    Weak  Yes
10        2        Mild   Normal  Strong  Yes
11        0        Mild     High  Strong  Yes
12        0         Hot   Normal    Weak  Yes
13        1        Mild     High  Strong   No

In [9]:
col = ['Temperature','Humidity','Windy','Play']
for i in col:
    df[i] = le.fit_transform(df[i])
df

    Outlook  Temperature  Humidity  Windy  Play
0         2            1         0      1     0
1         2            1         0      0     0
2         0            1         0      1     1
3         1            2         0      1     1
4         1            0         1      1     1
5         1            0         1      0     0
6         0            0         1      0     1
7         2            2         0      1     0
8         2            0         1      1     1
9         1            2         1      1     1
10        2            2         1      0     1
11        0            2         0      0     1
12        0            1         1      1     1
13        1            2         0      0     0

In [10]:
d1=pd.read_excel(r"C:\Users\Yuvaraj S\OneDrive\Desktop\16MLP\weather_forecast.xlsx")
d1

     Outlook Temperature Humidity   Windy Play
0      Sunny         Hot     High    Weak   No
1      Sunny         Hot     High  Strong   No
2   Overcast         Hot     High    Weak  Yes
3       Rain        Mild     High    Weak  Yes
4       Rain        Cool   Normal    Weak  Yes
5       Rain        Cool   Normal  Strong   No
6   Overcast        Cool   Normal  Strong  Yes
7      Sunny        Mild     High    Weak   No
8      Sunny        Cool   Normal    Weak  Yes
9       Rain        Mild   Normal    Weak  Yes
10     Sunny        Mild   Normal  Strong  Yes
11  Overcast        Mild     High  Strong  Yes
12  Overcast         Hot   Normal    Weak  Yes
13      Rain        Mild     High  Strong   No

In [11]:
l1 = d1.columns
l1

Index(['Outlook', 'Temperature', 'Humidity', 'Windy', 'Play'], dtype='object')

In [12]:
encoded_df=pd.get_dummies(d1,dtype=int)
encoded_df

,Outlook_Overcast,Outlook_Rain,Outlook_Sunny,Temperature_Cool,Temperature_Hot,Temperature_Mild,Humidity_High,Humidity_Normal,Windy_Strong,Windy_Weak,Play_No,Play_Yes
0,0,0,1,0,1,0,1,0,0,1,1,0
1,0,0,1,0,1,0,1,0,1,0,1,0
2,1,0,0,0,1,0,1,0,0,1,0,1
3,0,1,0,0,0,1,1,0,0,1,0,1
4,0,1,0,1,0,0,0,1,0,1,0,1
5,0,1,0,1,0,0,0,1,1,0,1,0
6,1,0,0,1,0,0,0,1,1,0,0,1
7,0,0,1,0,0,1,1,0,0,1,1,0
8,0,0,1,1,0,0,0,1,0,1,0,1
9,0,1,0,0,0,1,0,1,0,1,0,1
10,0,0,1,0,0,1,0,1,1,0,0,1
11,1,0,0,0,0,1,1,0,1,0,0,1
12,1,0,0,0,1,0,0,1,0,1,0,1
13,0,1,0,0,0,1,1,0,1,0,1,0